return {
  {
    "williamboman/mason.nvim",
    cmd = "Mason",
    build = ":MasonUpdate",
    opts = {},
  },
  {
    "williamboman/mason-lspconfig.nvim",
    dependencies = { "williamboman/mason.nvim" },
    opts = {
      ensure_installed = {
        "pyright",
        "ts_ls",
        "texlab",
        "jdtls",
        "clangd",
        "lua_ls",
        "jsonls",
        "yamlls",
        "eslint",
        "prismals",
        "html",
        "cssls",
        "astro",
        "emmet_language_server",
      },
      automatic_enable = false,
    },
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    dependencies = { "williamboman/mason.nvim" },
    opts = {
      ensure_installed = {
        "prettier",
        "eslint_d",
        "ruff",
        "black",
        "stylua",
        "clang-format",
        "latexindent",
      },
      auto_update = false,
      run_on_start = true,
      start_delay = 3000,
      debounce_hours = 24,
    },
  },
}
