#!/bin/bash
# Encuentra el controlador xhci
ls /sys/bus/pci/drivers/xhci_hcd/

# Desconecta y reconecta el controlador
echo '0000:00:14.0' | sudo tee /sys/bus/pci/drivers/xhci_hcd/unbind
sleep 2
echo '0000:00:14.0' | sudo tee /sys/bus/pci/drivers/xhci_hcd/bind
