#!/bin/bash

# Obtener el tamaño de la pantalla
SCREEN_WIDTH=$(xdpyinfo | awk '/dimensions/{print $2}' | cut -d'x' -f1)
SCREEN_HEIGHT=$(xdpyinfo | awk '/dimensions/{print $2}' | cut -d'x' -f2)

# Calcular un cuarto del tamaño de la pantalla
WIN_WIDTH=$((SCREEN_WIDTH / 2))
WIN_HEIGHT=$((SCREEN_HEIGHT / 2))

# Calcular posición centrada
X_POS=$(( (SCREEN_WIDTH - WIN_WIDTH) / 2 ))
Y_POS=$(( (SCREEN_HEIGHT - WIN_HEIGHT) / 2 ))

# Obtener la ventana activa
WIN_ID=$(xdotool getactivewindow)

# Simular Super + G para hacerla flotante
xdotool key Super+g
sleep 0.2  # Pequeña pausa para asegurar que se active el modo flotante

# Cambiar tamaño y posición
wmctrl -ir "$WIN_ID" -e 0,$X_POS,$Y_POS,$WIN_WIDTH,$WIN_HEIGHT

