#!/bin/bash

# Basic

load_basic_utilities() {
  touch .nvim.lua
  mkdir .vim
  touch ./.vim/coc-settings.json
}

# Default if there is not argument
#

if [ -z "$1" ]; then
  load_basic_utilities
  exit 0
fi

touch .nvimrc
mkdir .vim
touch ./.vim/coc-settings.json
touch .gitignore

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  git init
fi

echo "
*.nvimrc
*.vim
" >> .gitignore

git add .gitignore

git commit -m "Initialized configuration and repository files"
